<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ApplicationIcon>camera-icon.ico</ApplicationIcon>
    <SignAssembly>False</SignAssembly>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="camera-icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="camera-icon.ico" />
  </ItemGroup>

</Project>
