<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ApplicationIcon>camera-icon.ico</ApplicationIcon>
    <SignAssembly>False</SignAssembly>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="camera-icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="camera-icon.ico" />
  </ItemGroup>

</Project>
